add some more dependencies based on run-time exceptions Even with this, there are more run-time `java.lang.NoClassDefFoundError` exceptions thrown, indicating that we need to add even more dependencies to the `build.gradle` file.